/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(DISTINCT customer_id) as total_number_of_customers
FROM Gold.dim_customers
GROUP BY country;
    

-- Find total customers by gender
SELECT
    gender,
    COUNT(DISTINCT customer_id) as total_number_of_customers
FROM Gold.dim_customers
GROUP BY gender;
    

-- Find total products by category
SELECT
    category,
    COUNT(DISTINCT product_id) as total_number_of_products
FROM Gold.dim_products
GROUP BY category;

-- What is the average costs in each category?
SELECT
    category,
    SUM(cost) as total_cost
FROM Gold.dim_products
GROUP BY category;

-- What is the total revenue generated for each category?
SELECT
    gdp.category,
    SUM(gfs.sales_amount) as total_revenue
FROM Gold.dim_products as gdp
LEFT JOIN Gold.fact_sales as gfs 
    ON gdp.product_key = gfs.product_key
GROUP BY gdp.category
ORDER BY SUM(gfs.sales_amount) DESC;


-- What is the total revenue generated by each customer?
SELECT
    gdc.customer_key,
    SUM(gfs.sales_amount) as total_revenue
FROM Gold.dim_customers as gdc
LEFT JOIN Gold.fact_sales as gfs 
    ON gdc.customer_key = gfs.customer_key
GROUP BY gdc.customer_key
ORDER BY SUM(gfs.sales_amount) DESC;
use datawarehouse;
-- What is the distribution of sold items across countries?
SELECT
    gdc.country,
    SUM(gfs.quantity) as total_sold_items
FROM Gold.fact_sales as gfs
LEFT JOIN Gold.dim_customers as gdc
    ON gfs.customer_key = gdc.customer_key
GROUP BY gdc.country
ORDER BY SUM(gfs.quantity) DESC;
